// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pika.proto

package pikaproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_kMetaSync        Type = 1
	Type_kTrySync         Type = 2
	Type_kDBSync          Type = 3
	Type_kBinlogSync      Type = 4
	Type_kHeatBeat        Type = 5
	Type_kRemoveSlaveNode Type = 6
)

var Type_name = map[int32]string{
	1: "kMetaSync",
	2: "kTrySync",
	3: "kDBSync",
	4: "kBinlogSync",
	5: "kHeatBeat",
	6: "kRemoveSlaveNode",
}

var Type_value = map[string]int32{
	"kMetaSync":        1,
	"kTrySync":         2,
	"kDBSync":          3,
	"kBinlogSync":      4,
	"kHeatBeat":        5,
	"kRemoveSlaveNode": 6,
}

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (x *Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_value, data, "Type")
	if err != nil {
		return err
	}
	*x = Type(value)
	return nil
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{0}
}

type StatusCode int32

const (
	StatusCode_kOk    StatusCode = 1
	StatusCode_kError StatusCode = 2
)

var StatusCode_name = map[int32]string{
	1: "kOk",
	2: "kError",
}

var StatusCode_value = map[string]int32{
	"kOk":    1,
	"kError": 2,
}

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (x *StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusCode_value, data, "StatusCode")
	if err != nil {
		return err
	}
	*x = StatusCode(value)
	return nil
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{1}
}

type InnerResponse_TrySync_ReplyCode int32

const (
	InnerResponse_TrySync_kOk                InnerResponse_TrySync_ReplyCode = 1
	InnerResponse_TrySync_kSyncPointBePurged InnerResponse_TrySync_ReplyCode = 2
	InnerResponse_TrySync_kSyncPointLarger   InnerResponse_TrySync_ReplyCode = 3
	InnerResponse_TrySync_kError             InnerResponse_TrySync_ReplyCode = 4
)

var InnerResponse_TrySync_ReplyCode_name = map[int32]string{
	1: "kOk",
	2: "kSyncPointBePurged",
	3: "kSyncPointLarger",
	4: "kError",
}

var InnerResponse_TrySync_ReplyCode_value = map[string]int32{
	"kOk":                1,
	"kSyncPointBePurged": 2,
	"kSyncPointLarger":   3,
	"kError":             4,
}

func (x InnerResponse_TrySync_ReplyCode) Enum() *InnerResponse_TrySync_ReplyCode {
	p := new(InnerResponse_TrySync_ReplyCode)
	*p = x
	return p
}

func (x InnerResponse_TrySync_ReplyCode) String() string {
	return proto.EnumName(InnerResponse_TrySync_ReplyCode_name, int32(x))
}

func (x *InnerResponse_TrySync_ReplyCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InnerResponse_TrySync_ReplyCode_value, data, "InnerResponse_TrySync_ReplyCode")
	if err != nil {
		return err
	}
	*x = InnerResponse_TrySync_ReplyCode(value)
	return nil
}

func (InnerResponse_TrySync_ReplyCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 1, 0}
}

type BinlogOffset struct {
	Filenum              *uint32  `protobuf:"varint,1,req,name=filenum" json:"filenum,omitempty"`
	Offset               *uint64  `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinlogOffset) Reset()         { *m = BinlogOffset{} }
func (m *BinlogOffset) String() string { return proto.CompactTextString(m) }
func (*BinlogOffset) ProtoMessage()    {}
func (*BinlogOffset) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{0}
}

func (m *BinlogOffset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinlogOffset.Unmarshal(m, b)
}
func (m *BinlogOffset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinlogOffset.Marshal(b, m, deterministic)
}
func (m *BinlogOffset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinlogOffset.Merge(m, src)
}
func (m *BinlogOffset) XXX_Size() int {
	return xxx_messageInfo_BinlogOffset.Size(m)
}
func (m *BinlogOffset) XXX_DiscardUnknown() {
	xxx_messageInfo_BinlogOffset.DiscardUnknown(m)
}

var xxx_messageInfo_BinlogOffset proto.InternalMessageInfo

func (m *BinlogOffset) GetFilenum() uint32 {
	if m != nil && m.Filenum != nil {
		return *m.Filenum
	}
	return 0
}

func (m *BinlogOffset) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

type Node struct {
	Ip                   *string  `protobuf:"bytes,1,req,name=ip" json:"ip,omitempty"`
	Port                 *int32   `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type Partition struct {
	TableName            *string  `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	PartitionId          *uint32  `protobuf:"varint,2,req,name=partition_id,json=partitionId" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{2}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *Partition) GetPartitionId() uint32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

type TableInfo struct {
	TableName            *string  `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	PartitionNum         *uint32  `protobuf:"varint,2,req,name=partition_num,json=partitionNum" json:"partition_num,omitempty"`
	PartitionIds         []uint32 `protobuf:"varint,3,rep,name=partition_ids,json=partitionIds" json:"partition_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableInfo) Reset()         { *m = TableInfo{} }
func (m *TableInfo) String() string { return proto.CompactTextString(m) }
func (*TableInfo) ProtoMessage()    {}
func (*TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{3}
}

func (m *TableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableInfo.Unmarshal(m, b)
}
func (m *TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableInfo.Marshal(b, m, deterministic)
}
func (m *TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableInfo.Merge(m, src)
}
func (m *TableInfo) XXX_Size() int {
	return xxx_messageInfo_TableInfo.Size(m)
}
func (m *TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TableInfo proto.InternalMessageInfo

func (m *TableInfo) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInfo) GetPartitionNum() uint32 {
	if m != nil && m.PartitionNum != nil {
		return *m.PartitionNum
	}
	return 0
}

func (m *TableInfo) GetPartitionIds() []uint32 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

type PikaMeta struct {
	TableInfos           []*TableInfo `protobuf:"bytes,1,rep,name=table_infos,json=tableInfos" json:"table_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PikaMeta) Reset()         { *m = PikaMeta{} }
func (m *PikaMeta) String() string { return proto.CompactTextString(m) }
func (*PikaMeta) ProtoMessage()    {}
func (*PikaMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{4}
}

func (m *PikaMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PikaMeta.Unmarshal(m, b)
}
func (m *PikaMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PikaMeta.Marshal(b, m, deterministic)
}
func (m *PikaMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PikaMeta.Merge(m, src)
}
func (m *PikaMeta) XXX_Size() int {
	return xxx_messageInfo_PikaMeta.Size(m)
}
func (m *PikaMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PikaMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PikaMeta proto.InternalMessageInfo

func (m *PikaMeta) GetTableInfos() []*TableInfo {
	if m != nil {
		return m.TableInfos
	}
	return nil
}

type InnerRequest struct {
	Type                 *Type                           `protobuf:"varint,1,req,name=type,enum=pikaproto.Type" json:"type,omitempty"`
	MetaSync             *InnerRequest_MetaSync          `protobuf:"bytes,2,opt,name=meta_sync,json=metaSync" json:"meta_sync,omitempty"`
	TrySync              *InnerRequest_TrySync           `protobuf:"bytes,3,opt,name=try_sync,json=trySync" json:"try_sync,omitempty"`
	DbSync               *InnerRequest_DBSync            `protobuf:"bytes,4,opt,name=db_sync,json=dbSync" json:"db_sync,omitempty"`
	BinlogSync           *InnerRequest_BinlogSync        `protobuf:"bytes,5,opt,name=binlog_sync,json=binlogSync" json:"binlog_sync,omitempty"`
	RemoveSlaveNode      []*InnerRequest_RemoveSlaveNode `protobuf:"bytes,6,rep,name=remove_slave_node,json=removeSlaveNode" json:"remove_slave_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *InnerRequest) Reset()         { *m = InnerRequest{} }
func (m *InnerRequest) String() string { return proto.CompactTextString(m) }
func (*InnerRequest) ProtoMessage()    {}
func (*InnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{5}
}

func (m *InnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest.Unmarshal(m, b)
}
func (m *InnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest.Marshal(b, m, deterministic)
}
func (m *InnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest.Merge(m, src)
}
func (m *InnerRequest) XXX_Size() int {
	return xxx_messageInfo_InnerRequest.Size(m)
}
func (m *InnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest proto.InternalMessageInfo

func (m *InnerRequest) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_kMetaSync
}

func (m *InnerRequest) GetMetaSync() *InnerRequest_MetaSync {
	if m != nil {
		return m.MetaSync
	}
	return nil
}

func (m *InnerRequest) GetTrySync() *InnerRequest_TrySync {
	if m != nil {
		return m.TrySync
	}
	return nil
}

func (m *InnerRequest) GetDbSync() *InnerRequest_DBSync {
	if m != nil {
		return m.DbSync
	}
	return nil
}

func (m *InnerRequest) GetBinlogSync() *InnerRequest_BinlogSync {
	if m != nil {
		return m.BinlogSync
	}
	return nil
}

func (m *InnerRequest) GetRemoveSlaveNode() []*InnerRequest_RemoveSlaveNode {
	if m != nil {
		return m.RemoveSlaveNode
	}
	return nil
}

type InnerRequest_MetaSync struct {
	Node                 *Node    `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Auth                 *string  `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerRequest_MetaSync) Reset()         { *m = InnerRequest_MetaSync{} }
func (m *InnerRequest_MetaSync) String() string { return proto.CompactTextString(m) }
func (*InnerRequest_MetaSync) ProtoMessage()    {}
func (*InnerRequest_MetaSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{5, 0}
}

func (m *InnerRequest_MetaSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest_MetaSync.Unmarshal(m, b)
}
func (m *InnerRequest_MetaSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest_MetaSync.Marshal(b, m, deterministic)
}
func (m *InnerRequest_MetaSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest_MetaSync.Merge(m, src)
}
func (m *InnerRequest_MetaSync) XXX_Size() int {
	return xxx_messageInfo_InnerRequest_MetaSync.Size(m)
}
func (m *InnerRequest_MetaSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest_MetaSync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest_MetaSync proto.InternalMessageInfo

func (m *InnerRequest_MetaSync) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *InnerRequest_MetaSync) GetAuth() string {
	if m != nil && m.Auth != nil {
		return *m.Auth
	}
	return ""
}

type InnerRequest_TrySync struct {
	Node                 *Node         `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Partition            *Partition    `protobuf:"bytes,2,req,name=partition" json:"partition,omitempty"`
	BinlogOffset         *BinlogOffset `protobuf:"bytes,3,req,name=binlog_offset,json=binlogOffset" json:"binlog_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InnerRequest_TrySync) Reset()         { *m = InnerRequest_TrySync{} }
func (m *InnerRequest_TrySync) String() string { return proto.CompactTextString(m) }
func (*InnerRequest_TrySync) ProtoMessage()    {}
func (*InnerRequest_TrySync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{5, 1}
}

func (m *InnerRequest_TrySync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest_TrySync.Unmarshal(m, b)
}
func (m *InnerRequest_TrySync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest_TrySync.Marshal(b, m, deterministic)
}
func (m *InnerRequest_TrySync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest_TrySync.Merge(m, src)
}
func (m *InnerRequest_TrySync) XXX_Size() int {
	return xxx_messageInfo_InnerRequest_TrySync.Size(m)
}
func (m *InnerRequest_TrySync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest_TrySync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest_TrySync proto.InternalMessageInfo

func (m *InnerRequest_TrySync) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *InnerRequest_TrySync) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *InnerRequest_TrySync) GetBinlogOffset() *BinlogOffset {
	if m != nil {
		return m.BinlogOffset
	}
	return nil
}

type InnerRequest_DBSync struct {
	Node                 *Node         `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Partition            *Partition    `protobuf:"bytes,2,req,name=partition" json:"partition,omitempty"`
	BinlogOffset         *BinlogOffset `protobuf:"bytes,3,req,name=binlog_offset,json=binlogOffset" json:"binlog_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InnerRequest_DBSync) Reset()         { *m = InnerRequest_DBSync{} }
func (m *InnerRequest_DBSync) String() string { return proto.CompactTextString(m) }
func (*InnerRequest_DBSync) ProtoMessage()    {}
func (*InnerRequest_DBSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{5, 2}
}

func (m *InnerRequest_DBSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest_DBSync.Unmarshal(m, b)
}
func (m *InnerRequest_DBSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest_DBSync.Marshal(b, m, deterministic)
}
func (m *InnerRequest_DBSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest_DBSync.Merge(m, src)
}
func (m *InnerRequest_DBSync) XXX_Size() int {
	return xxx_messageInfo_InnerRequest_DBSync.Size(m)
}
func (m *InnerRequest_DBSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest_DBSync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest_DBSync proto.InternalMessageInfo

func (m *InnerRequest_DBSync) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *InnerRequest_DBSync) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *InnerRequest_DBSync) GetBinlogOffset() *BinlogOffset {
	if m != nil {
		return m.BinlogOffset
	}
	return nil
}

type InnerRequest_BinlogSync struct {
	Node                 *Node         `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	TableName            *string       `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	PartitionId          *uint32       `protobuf:"varint,3,req,name=partition_id,json=partitionId" json:"partition_id,omitempty"`
	AckRangeStart        *BinlogOffset `protobuf:"bytes,4,req,name=ack_range_start,json=ackRangeStart" json:"ack_range_start,omitempty"`
	AckRangeEnd          *BinlogOffset `protobuf:"bytes,5,req,name=ack_range_end,json=ackRangeEnd" json:"ack_range_end,omitempty"`
	SessionId            *int32        `protobuf:"varint,6,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	FirstSend            *bool         `protobuf:"varint,7,req,name=first_send,json=firstSend" json:"first_send,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InnerRequest_BinlogSync) Reset()         { *m = InnerRequest_BinlogSync{} }
func (m *InnerRequest_BinlogSync) String() string { return proto.CompactTextString(m) }
func (*InnerRequest_BinlogSync) ProtoMessage()    {}
func (*InnerRequest_BinlogSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{5, 3}
}

func (m *InnerRequest_BinlogSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest_BinlogSync.Unmarshal(m, b)
}
func (m *InnerRequest_BinlogSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest_BinlogSync.Marshal(b, m, deterministic)
}
func (m *InnerRequest_BinlogSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest_BinlogSync.Merge(m, src)
}
func (m *InnerRequest_BinlogSync) XXX_Size() int {
	return xxx_messageInfo_InnerRequest_BinlogSync.Size(m)
}
func (m *InnerRequest_BinlogSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest_BinlogSync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest_BinlogSync proto.InternalMessageInfo

func (m *InnerRequest_BinlogSync) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *InnerRequest_BinlogSync) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *InnerRequest_BinlogSync) GetPartitionId() uint32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *InnerRequest_BinlogSync) GetAckRangeStart() *BinlogOffset {
	if m != nil {
		return m.AckRangeStart
	}
	return nil
}

func (m *InnerRequest_BinlogSync) GetAckRangeEnd() *BinlogOffset {
	if m != nil {
		return m.AckRangeEnd
	}
	return nil
}

func (m *InnerRequest_BinlogSync) GetSessionId() int32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *InnerRequest_BinlogSync) GetFirstSend() bool {
	if m != nil && m.FirstSend != nil {
		return *m.FirstSend
	}
	return false
}

type InnerRequest_RemoveSlaveNode struct {
	Node                 *Node      `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Partition            *Partition `protobuf:"bytes,2,req,name=partition" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InnerRequest_RemoveSlaveNode) Reset()         { *m = InnerRequest_RemoveSlaveNode{} }
func (m *InnerRequest_RemoveSlaveNode) String() string { return proto.CompactTextString(m) }
func (*InnerRequest_RemoveSlaveNode) ProtoMessage()    {}
func (*InnerRequest_RemoveSlaveNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{5, 4}
}

func (m *InnerRequest_RemoveSlaveNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest_RemoveSlaveNode.Unmarshal(m, b)
}
func (m *InnerRequest_RemoveSlaveNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest_RemoveSlaveNode.Marshal(b, m, deterministic)
}
func (m *InnerRequest_RemoveSlaveNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest_RemoveSlaveNode.Merge(m, src)
}
func (m *InnerRequest_RemoveSlaveNode) XXX_Size() int {
	return xxx_messageInfo_InnerRequest_RemoveSlaveNode.Size(m)
}
func (m *InnerRequest_RemoveSlaveNode) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest_RemoveSlaveNode.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest_RemoveSlaveNode proto.InternalMessageInfo

func (m *InnerRequest_RemoveSlaveNode) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *InnerRequest_RemoveSlaveNode) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

type PartitionInfo struct {
	PartitionId          *uint32  `protobuf:"varint,1,req,name=partition_id,json=partitionId" json:"partition_id,omitempty"`
	Master               *Node    `protobuf:"bytes,2,req,name=master" json:"master,omitempty"`
	Slaves               []*Node  `protobuf:"bytes,3,rep,name=slaves" json:"slaves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionInfo) Reset()         { *m = PartitionInfo{} }
func (m *PartitionInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionInfo) ProtoMessage()    {}
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{6}
}

func (m *PartitionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionInfo.Unmarshal(m, b)
}
func (m *PartitionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionInfo.Marshal(b, m, deterministic)
}
func (m *PartitionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionInfo.Merge(m, src)
}
func (m *PartitionInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionInfo.Size(m)
}
func (m *PartitionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionInfo proto.InternalMessageInfo

func (m *PartitionInfo) GetPartitionId() uint32 {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return 0
}

func (m *PartitionInfo) GetMaster() *Node {
	if m != nil {
		return m.Master
	}
	return nil
}

func (m *PartitionInfo) GetSlaves() []*Node {
	if m != nil {
		return m.Slaves
	}
	return nil
}

type InnerResponse struct {
	Type                 *Type                            `protobuf:"varint,1,req,name=type,enum=pikaproto.Type" json:"type,omitempty"`
	Code                 *StatusCode                      `protobuf:"varint,2,req,name=code,enum=pikaproto.StatusCode" json:"code,omitempty"`
	Reply                *string                          `protobuf:"bytes,3,opt,name=reply" json:"reply,omitempty"`
	MetaSync             *InnerResponse_MetaSync          `protobuf:"bytes,4,opt,name=meta_sync,json=metaSync" json:"meta_sync,omitempty"`
	DbSync               *InnerResponse_DBSync            `protobuf:"bytes,5,opt,name=db_sync,json=dbSync" json:"db_sync,omitempty"`
	TrySync              *InnerResponse_TrySync           `protobuf:"bytes,6,opt,name=try_sync,json=trySync" json:"try_sync,omitempty"`
	BinlogSync           []*InnerResponse_BinlogSync      `protobuf:"bytes,7,rep,name=binlog_sync,json=binlogSync" json:"binlog_sync,omitempty"`
	RemoveSlaveNode      []*InnerResponse_RemoveSlaveNode `protobuf:"bytes,8,rep,name=remove_slave_node,json=removeSlaveNode" json:"remove_slave_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InnerResponse) Reset()         { *m = InnerResponse{} }
func (m *InnerResponse) String() string { return proto.CompactTextString(m) }
func (*InnerResponse) ProtoMessage()    {}
func (*InnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7}
}

func (m *InnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse.Unmarshal(m, b)
}
func (m *InnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse.Marshal(b, m, deterministic)
}
func (m *InnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse.Merge(m, src)
}
func (m *InnerResponse) XXX_Size() int {
	return xxx_messageInfo_InnerResponse.Size(m)
}
func (m *InnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse proto.InternalMessageInfo

func (m *InnerResponse) GetType() Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Type_kMetaSync
}

func (m *InnerResponse) GetCode() StatusCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return StatusCode_kOk
}

func (m *InnerResponse) GetReply() string {
	if m != nil && m.Reply != nil {
		return *m.Reply
	}
	return ""
}

func (m *InnerResponse) GetMetaSync() *InnerResponse_MetaSync {
	if m != nil {
		return m.MetaSync
	}
	return nil
}

func (m *InnerResponse) GetDbSync() *InnerResponse_DBSync {
	if m != nil {
		return m.DbSync
	}
	return nil
}

func (m *InnerResponse) GetTrySync() *InnerResponse_TrySync {
	if m != nil {
		return m.TrySync
	}
	return nil
}

func (m *InnerResponse) GetBinlogSync() []*InnerResponse_BinlogSync {
	if m != nil {
		return m.BinlogSync
	}
	return nil
}

func (m *InnerResponse) GetRemoveSlaveNode() []*InnerResponse_RemoveSlaveNode {
	if m != nil {
		return m.RemoveSlaveNode
	}
	return nil
}

type InnerResponse_MetaSync struct {
	ClassicMode          *bool                               `protobuf:"varint,1,req,name=classic_mode,json=classicMode" json:"classic_mode,omitempty"`
	TablesInfo           []*InnerResponse_MetaSync_TableInfo `protobuf:"bytes,2,rep,name=tables_info,json=tablesInfo" json:"tables_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *InnerResponse_MetaSync) Reset()         { *m = InnerResponse_MetaSync{} }
func (m *InnerResponse_MetaSync) String() string { return proto.CompactTextString(m) }
func (*InnerResponse_MetaSync) ProtoMessage()    {}
func (*InnerResponse_MetaSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 0}
}

func (m *InnerResponse_MetaSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse_MetaSync.Unmarshal(m, b)
}
func (m *InnerResponse_MetaSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse_MetaSync.Marshal(b, m, deterministic)
}
func (m *InnerResponse_MetaSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse_MetaSync.Merge(m, src)
}
func (m *InnerResponse_MetaSync) XXX_Size() int {
	return xxx_messageInfo_InnerResponse_MetaSync.Size(m)
}
func (m *InnerResponse_MetaSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse_MetaSync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse_MetaSync proto.InternalMessageInfo

func (m *InnerResponse_MetaSync) GetClassicMode() bool {
	if m != nil && m.ClassicMode != nil {
		return *m.ClassicMode
	}
	return false
}

func (m *InnerResponse_MetaSync) GetTablesInfo() []*InnerResponse_MetaSync_TableInfo {
	if m != nil {
		return m.TablesInfo
	}
	return nil
}

type InnerResponse_MetaSync_TableInfo struct {
	TableName            *string  `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	PartitionNum         *int32   `protobuf:"varint,2,req,name=partition_num,json=partitionNum" json:"partition_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerResponse_MetaSync_TableInfo) Reset()         { *m = InnerResponse_MetaSync_TableInfo{} }
func (m *InnerResponse_MetaSync_TableInfo) String() string { return proto.CompactTextString(m) }
func (*InnerResponse_MetaSync_TableInfo) ProtoMessage()    {}
func (*InnerResponse_MetaSync_TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 0, 0}
}

func (m *InnerResponse_MetaSync_TableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse_MetaSync_TableInfo.Unmarshal(m, b)
}
func (m *InnerResponse_MetaSync_TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse_MetaSync_TableInfo.Marshal(b, m, deterministic)
}
func (m *InnerResponse_MetaSync_TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse_MetaSync_TableInfo.Merge(m, src)
}
func (m *InnerResponse_MetaSync_TableInfo) XXX_Size() int {
	return xxx_messageInfo_InnerResponse_MetaSync_TableInfo.Size(m)
}
func (m *InnerResponse_MetaSync_TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse_MetaSync_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse_MetaSync_TableInfo proto.InternalMessageInfo

func (m *InnerResponse_MetaSync_TableInfo) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *InnerResponse_MetaSync_TableInfo) GetPartitionNum() int32 {
	if m != nil && m.PartitionNum != nil {
		return *m.PartitionNum
	}
	return 0
}

type InnerResponse_TrySync struct {
	ReplyCode            *InnerResponse_TrySync_ReplyCode `protobuf:"varint,1,req,name=reply_code,json=replyCode,enum=pikaproto.InnerResponse_TrySync_ReplyCode" json:"reply_code,omitempty"`
	Partition            *Partition                       `protobuf:"bytes,2,req,name=partition" json:"partition,omitempty"`
	BinlogOffset         *BinlogOffset                    `protobuf:"bytes,3,opt,name=binlog_offset,json=binlogOffset" json:"binlog_offset,omitempty"`
	SessionId            *int32                           `protobuf:"varint,4,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InnerResponse_TrySync) Reset()         { *m = InnerResponse_TrySync{} }
func (m *InnerResponse_TrySync) String() string { return proto.CompactTextString(m) }
func (*InnerResponse_TrySync) ProtoMessage()    {}
func (*InnerResponse_TrySync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 1}
}

func (m *InnerResponse_TrySync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse_TrySync.Unmarshal(m, b)
}
func (m *InnerResponse_TrySync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse_TrySync.Marshal(b, m, deterministic)
}
func (m *InnerResponse_TrySync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse_TrySync.Merge(m, src)
}
func (m *InnerResponse_TrySync) XXX_Size() int {
	return xxx_messageInfo_InnerResponse_TrySync.Size(m)
}
func (m *InnerResponse_TrySync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse_TrySync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse_TrySync proto.InternalMessageInfo

func (m *InnerResponse_TrySync) GetReplyCode() InnerResponse_TrySync_ReplyCode {
	if m != nil && m.ReplyCode != nil {
		return *m.ReplyCode
	}
	return InnerResponse_TrySync_kOk
}

func (m *InnerResponse_TrySync) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *InnerResponse_TrySync) GetBinlogOffset() *BinlogOffset {
	if m != nil {
		return m.BinlogOffset
	}
	return nil
}

func (m *InnerResponse_TrySync) GetSessionId() int32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type InnerResponse_DBSync struct {
	Partition            *Partition `protobuf:"bytes,1,req,name=partition" json:"partition,omitempty"`
	SessionId            *int32     `protobuf:"varint,2,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InnerResponse_DBSync) Reset()         { *m = InnerResponse_DBSync{} }
func (m *InnerResponse_DBSync) String() string { return proto.CompactTextString(m) }
func (*InnerResponse_DBSync) ProtoMessage()    {}
func (*InnerResponse_DBSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 2}
}

func (m *InnerResponse_DBSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse_DBSync.Unmarshal(m, b)
}
func (m *InnerResponse_DBSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse_DBSync.Marshal(b, m, deterministic)
}
func (m *InnerResponse_DBSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse_DBSync.Merge(m, src)
}
func (m *InnerResponse_DBSync) XXX_Size() int {
	return xxx_messageInfo_InnerResponse_DBSync.Size(m)
}
func (m *InnerResponse_DBSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse_DBSync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse_DBSync proto.InternalMessageInfo

func (m *InnerResponse_DBSync) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *InnerResponse_DBSync) GetSessionId() int32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type InnerResponse_BinlogSync struct {
	Partition            *Partition    `protobuf:"bytes,1,req,name=partition" json:"partition,omitempty"`
	BinlogOffset         *BinlogOffset `protobuf:"bytes,2,req,name=binlog_offset,json=binlogOffset" json:"binlog_offset,omitempty"`
	Binlog               []byte        `protobuf:"bytes,3,req,name=binlog" json:"binlog,omitempty"`
	SessionId            *int32        `protobuf:"varint,4,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InnerResponse_BinlogSync) Reset()         { *m = InnerResponse_BinlogSync{} }
func (m *InnerResponse_BinlogSync) String() string { return proto.CompactTextString(m) }
func (*InnerResponse_BinlogSync) ProtoMessage()    {}
func (*InnerResponse_BinlogSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 3}
}

func (m *InnerResponse_BinlogSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse_BinlogSync.Unmarshal(m, b)
}
func (m *InnerResponse_BinlogSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse_BinlogSync.Marshal(b, m, deterministic)
}
func (m *InnerResponse_BinlogSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse_BinlogSync.Merge(m, src)
}
func (m *InnerResponse_BinlogSync) XXX_Size() int {
	return xxx_messageInfo_InnerResponse_BinlogSync.Size(m)
}
func (m *InnerResponse_BinlogSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse_BinlogSync.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse_BinlogSync proto.InternalMessageInfo

func (m *InnerResponse_BinlogSync) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *InnerResponse_BinlogSync) GetBinlogOffset() *BinlogOffset {
	if m != nil {
		return m.BinlogOffset
	}
	return nil
}

func (m *InnerResponse_BinlogSync) GetBinlog() []byte {
	if m != nil {
		return m.Binlog
	}
	return nil
}

func (m *InnerResponse_BinlogSync) GetSessionId() int32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type InnerResponse_RemoveSlaveNode struct {
	Node                 *Node      `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Partition            *Partition `protobuf:"bytes,2,req,name=partition" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InnerResponse_RemoveSlaveNode) Reset()         { *m = InnerResponse_RemoveSlaveNode{} }
func (m *InnerResponse_RemoveSlaveNode) String() string { return proto.CompactTextString(m) }
func (*InnerResponse_RemoveSlaveNode) ProtoMessage()    {}
func (*InnerResponse_RemoveSlaveNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_300a23a4a32800d9, []int{7, 4}
}

func (m *InnerResponse_RemoveSlaveNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerResponse_RemoveSlaveNode.Unmarshal(m, b)
}
func (m *InnerResponse_RemoveSlaveNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerResponse_RemoveSlaveNode.Marshal(b, m, deterministic)
}
func (m *InnerResponse_RemoveSlaveNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerResponse_RemoveSlaveNode.Merge(m, src)
}
func (m *InnerResponse_RemoveSlaveNode) XXX_Size() int {
	return xxx_messageInfo_InnerResponse_RemoveSlaveNode.Size(m)
}
func (m *InnerResponse_RemoveSlaveNode) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerResponse_RemoveSlaveNode.DiscardUnknown(m)
}

var xxx_messageInfo_InnerResponse_RemoveSlaveNode proto.InternalMessageInfo

func (m *InnerResponse_RemoveSlaveNode) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *InnerResponse_RemoveSlaveNode) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func init() {
	proto.RegisterEnum("pikaproto.Type", Type_name, Type_value)
	proto.RegisterEnum("pikaproto.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("pikaproto.InnerResponse_TrySync_ReplyCode", InnerResponse_TrySync_ReplyCode_name, InnerResponse_TrySync_ReplyCode_value)
	proto.RegisterType((*BinlogOffset)(nil), "pikaproto.BinlogOffset")
	proto.RegisterType((*Node)(nil), "pikaproto.Node")
	proto.RegisterType((*Partition)(nil), "pikaproto.Partition")
	proto.RegisterType((*TableInfo)(nil), "pikaproto.TableInfo")
	proto.RegisterType((*PikaMeta)(nil), "pikaproto.PikaMeta")
	proto.RegisterType((*InnerRequest)(nil), "pikaproto.InnerRequest")
	proto.RegisterType((*InnerRequest_MetaSync)(nil), "pikaproto.InnerRequest.MetaSync")
	proto.RegisterType((*InnerRequest_TrySync)(nil), "pikaproto.InnerRequest.TrySync")
	proto.RegisterType((*InnerRequest_DBSync)(nil), "pikaproto.InnerRequest.DBSync")
	proto.RegisterType((*InnerRequest_BinlogSync)(nil), "pikaproto.InnerRequest.BinlogSync")
	proto.RegisterType((*InnerRequest_RemoveSlaveNode)(nil), "pikaproto.InnerRequest.RemoveSlaveNode")
	proto.RegisterType((*PartitionInfo)(nil), "pikaproto.PartitionInfo")
	proto.RegisterType((*InnerResponse)(nil), "pikaproto.InnerResponse")
	proto.RegisterType((*InnerResponse_MetaSync)(nil), "pikaproto.InnerResponse.MetaSync")
	proto.RegisterType((*InnerResponse_MetaSync_TableInfo)(nil), "pikaproto.InnerResponse.MetaSync.TableInfo")
	proto.RegisterType((*InnerResponse_TrySync)(nil), "pikaproto.InnerResponse.TrySync")
	proto.RegisterType((*InnerResponse_DBSync)(nil), "pikaproto.InnerResponse.DBSync")
	proto.RegisterType((*InnerResponse_BinlogSync)(nil), "pikaproto.InnerResponse.BinlogSync")
	proto.RegisterType((*InnerResponse_RemoveSlaveNode)(nil), "pikaproto.InnerResponse.RemoveSlaveNode")
}

func init() { proto.RegisterFile("pika.proto", fileDescriptor_300a23a4a32800d9) }

var fileDescriptor_300a23a4a32800d9 = []byte{
	// 1012 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x6e, 0xe3, 0x36,
	0x14, 0x85, 0xe4, 0xa7, 0xae, 0xec, 0x44, 0x25, 0xd2, 0xa9, 0x60, 0xa0, 0xad, 0xa3, 0x2c, 0xc6,
	0x4d, 0x81, 0x2c, 0x02, 0x14, 0x2d, 0x3a, 0x7d, 0x26, 0x33, 0x40, 0x0d, 0x4c, 0x1e, 0xa0, 0xb3,
	0xeb, 0x42, 0xa0, 0x2d, 0x3a, 0x55, 0x65, 0x4b, 0x2a, 0x49, 0x0f, 0xe0, 0x7d, 0xff, 0xa3, 0xdd,
	0x76, 0xd5, 0xd5, 0xfc, 0x45, 0x17, 0xfd, 0xa4, 0x82, 0x57, 0xb2, 0x25, 0xd9, 0xf1, 0xc4, 0x7d,
	0xa2, 0xbb, 0x4b, 0xf2, 0x9c, 0xab, 0xcb, 0xc3, 0xcb, 0x43, 0x01, 0xa4, 0x61, 0xc4, 0xce, 0x52,
	0x91, 0xa8, 0x84, 0x58, 0x3a, 0xc6, 0xd0, 0xfb, 0x0a, 0x3a, 0x17, 0x61, 0x3c, 0x4b, 0xee, 0x6f,
	0xa6, 0x53, 0xc9, 0x15, 0x71, 0xa1, 0x35, 0x0d, 0x67, 0x3c, 0x5e, 0xcc, 0x5d, 0xa3, 0x6f, 0x0e,
	0xba, 0x74, 0x35, 0x24, 0x4f, 0xa0, 0x99, 0x20, 0xc6, 0x35, 0xfb, 0xe6, 0xa0, 0x4e, 0xf3, 0x91,
	0x77, 0x0a, 0xf5, 0xeb, 0x24, 0xe0, 0xe4, 0x00, 0xcc, 0x30, 0x45, 0x92, 0x45, 0xcd, 0x30, 0x25,
	0x04, 0xea, 0x69, 0x22, 0x32, 0x74, 0x83, 0x62, 0xec, 0x5d, 0x81, 0x75, 0xcb, 0x84, 0x0a, 0x55,
	0x98, 0xc4, 0xe4, 0x5d, 0x00, 0xc5, 0xc6, 0x33, 0xee, 0xc7, 0x6c, 0xce, 0x73, 0xa2, 0x85, 0x33,
	0xd7, 0x6c, 0xce, 0xc9, 0x31, 0x74, 0xd2, 0x15, 0xd6, 0x0f, 0x03, 0xcc, 0xd3, 0xa5, 0xf6, 0x7a,
	0x6e, 0x18, 0x78, 0x0a, 0xac, 0x3b, 0x8d, 0x1f, 0xc6, 0xd3, 0xe4, 0xb1, 0x74, 0x27, 0xd0, 0x2d,
	0xd2, 0xe9, 0xed, 0x65, 0xf9, 0x8a, 0x6f, 0x5c, 0x2f, 0xe6, 0x55, 0x50, 0x18, 0x48, 0xb7, 0xd6,
	0xaf, 0x55, 0x40, 0xc3, 0x40, 0x7a, 0x5f, 0x43, 0xfb, 0x36, 0x8c, 0xd8, 0x15, 0x57, 0x8c, 0x7c,
	0x04, 0x76, 0xf6, 0xd1, 0x30, 0x9e, 0x26, 0xd2, 0x35, 0xfa, 0xb5, 0x81, 0x7d, 0x7e, 0x74, 0xb6,
	0xd6, 0xf7, 0x6c, 0x5d, 0x1f, 0xcd, 0xaa, 0xd3, 0xa1, 0xf4, 0x7e, 0xb1, 0xa0, 0x33, 0x8c, 0x63,
	0x2e, 0x28, 0xff, 0x61, 0xc1, 0xa5, 0x22, 0x27, 0x50, 0x57, 0xcb, 0x34, 0x2b, 0xfb, 0xe0, 0xfc,
	0xb0, 0x9c, 0x60, 0x99, 0x72, 0x8a, 0x8b, 0xe4, 0x73, 0xb0, 0xe6, 0x5c, 0x31, 0x5f, 0x2e, 0xe3,
	0x89, 0x6b, 0xf6, 0x8d, 0x81, 0x7d, 0xde, 0x2f, 0x21, 0xcb, 0x09, 0xcf, 0x74, 0x75, 0xa3, 0x65,
	0x3c, 0xa1, 0xed, 0x79, 0x1e, 0x91, 0x4f, 0xa1, 0xad, 0xc4, 0x32, 0x63, 0xd7, 0x90, 0xfd, 0xfe,
	0x2e, 0xf6, 0x9d, 0x58, 0x22, 0xb9, 0xa5, 0xb2, 0x80, 0x7c, 0x0c, 0xad, 0x60, 0x9c, 0x51, 0xeb,
	0x48, 0x7d, 0x6f, 0x17, 0xf5, 0xf9, 0x05, 0x32, 0x9b, 0xc1, 0x18, 0x89, 0x97, 0x60, 0x8f, 0xb1,
	0xbf, 0x32, 0x72, 0x03, 0xc9, 0xde, 0x2e, 0x72, 0xd6, 0x8a, 0x98, 0x00, 0xc6, 0xeb, 0x98, 0x8c,
	0xe0, 0x2d, 0xc1, 0xe7, 0xc9, 0x2b, 0xee, 0xcb, 0x19, 0x7b, 0xc5, 0xfd, 0x38, 0x09, 0xb8, 0xdb,
	0x44, 0xad, 0x9f, 0xee, 0x4a, 0x45, 0x91, 0x30, 0xd2, 0x78, 0xdd, 0x9e, 0xf4, 0x50, 0x54, 0x27,
	0x7a, 0x97, 0xd0, 0x5e, 0x89, 0xa4, 0xe5, 0xc7, 0x9c, 0x5a, 0x7e, 0xbb, 0x22, 0x3f, 0x72, 0x71,
	0x51, 0x37, 0x34, 0x5b, 0xa8, 0xef, 0x50, 0x79, 0x8b, 0x62, 0xdc, 0xfb, 0xd9, 0x80, 0x56, 0x2e,
	0xd6, 0x7e, 0x49, 0xce, 0xc1, 0x5a, 0x37, 0x13, 0xb6, 0x60, 0xb5, 0x5d, 0xd6, 0xb7, 0x83, 0x16,
	0x30, 0xf2, 0x19, 0x74, 0x73, 0x0d, 0xf3, 0x0b, 0x58, 0x43, 0xde, 0x3b, 0x25, 0x5e, 0xf9, 0x0e,
	0xd3, 0xce, 0xb8, 0x34, 0xea, 0xfd, 0x64, 0x40, 0x33, 0x3b, 0x94, 0xff, 0x6b, 0x85, 0xbf, 0x9a,
	0x00, 0xc5, 0xc9, 0xef, 0x57, 0x65, 0xf5, 0xb6, 0x9b, 0x8f, 0x99, 0x47, 0x6d, 0xcb, 0x3c, 0xc8,
	0x97, 0x70, 0xc8, 0x26, 0x91, 0x2f, 0x58, 0x7c, 0xcf, 0x7d, 0xa9, 0x98, 0x50, 0x6e, 0xfd, 0xcd,
	0x55, 0x77, 0xd9, 0x24, 0xa2, 0x1a, 0x3e, 0xd2, 0x68, 0xf2, 0x0c, 0xba, 0x45, 0x02, 0x1e, 0x07,
	0x6e, 0xe3, 0xcd, 0x74, 0x7b, 0x45, 0x7f, 0x11, 0x07, 0xba, 0x7e, 0xc9, 0xa5, 0xcc, 0xcb, 0x6b,
	0xa2, 0x47, 0x5a, 0xf9, 0xcc, 0x10, 0x97, 0xa7, 0xa1, 0x90, 0xca, 0x97, 0x3a, 0x71, 0xab, 0x6f,
	0x0e, 0xda, 0xd4, 0xc2, 0x99, 0x11, 0x8f, 0x83, 0xde, 0xf7, 0x70, 0xb8, 0xd1, 0xdf, 0xff, 0xda,
	0xd9, 0x7a, 0x3f, 0x1a, 0xd0, 0x5d, 0x2f, 0xa0, 0xd3, 0x6e, 0x8a, 0x6b, 0x6c, 0x8b, 0xfb, 0x14,
	0x9a, 0x73, 0x26, 0x15, 0x17, 0xf9, 0x57, 0xb6, 0xea, 0xc9, 0x97, 0x35, 0x10, 0xef, 0x74, 0x66,
	0xb5, 0x0f, 0x01, 0xb3, 0x65, 0xef, 0x77, 0x80, 0x6e, 0x7e, 0xc1, 0x65, 0x9a, 0xc4, 0x92, 0xef,
	0xe7, 0x99, 0x1f, 0x40, 0x7d, 0xa2, 0x65, 0x31, 0x11, 0xf4, 0x76, 0x09, 0x34, 0x52, 0x4c, 0x2d,
	0xe4, 0x25, 0x8a, 0xa3, 0x21, 0xe4, 0x08, 0x1a, 0x82, 0xa7, 0xb3, 0x25, 0x9a, 0xa3, 0x45, 0xb3,
	0x01, 0xf9, 0xa2, 0x6c, 0xba, 0x99, 0xf7, 0x1d, 0x6f, 0x7b, 0x4e, 0x56, 0xd2, 0x43, 0xae, 0xfb,
	0x49, 0xe1, 0x9c, 0x8d, 0x5d, 0xa6, 0x9b, 0xb3, 0x37, 0xac, 0xf3, 0x59, 0xc9, 0xaf, 0x9b, 0xbb,
	0xdc, 0x3e, 0xa7, 0x6e, 0x19, 0xf6, 0xf3, 0xaa, 0xef, 0xb6, 0x50, 0xdc, 0x93, 0x9d, 0xfc, 0x1d,
	0xc6, 0x7b, 0xf7, 0x90, 0xf1, 0xb6, 0x31, 0xd7, 0x60, 0x67, 0xae, 0x47, 0x9d, 0xf7, 0x37, 0xa3,
	0x64, 0xbd, 0xc7, 0xd0, 0x99, 0xcc, 0x98, 0x94, 0xe1, 0xc4, 0x9f, 0xaf, 0xfa, 0xb7, 0x4d, 0xed,
	0x7c, 0xee, 0x4a, 0x1f, 0xcc, 0xcb, 0xfc, 0x91, 0x95, 0xf8, 0xca, 0xba, 0x26, 0x7e, 0xff, 0xc3,
	0x47, 0x0f, 0x61, 0xeb, 0xed, 0x95, 0x3a, 0xee, 0xdd, 0xfc, 0xdd, 0x9f, 0x86, 0x46, 0xf5, 0xa7,
	0xa1, 0xf7, 0xda, 0x2c, 0xde, 0x80, 0x21, 0x00, 0xb6, 0x8d, 0x3f, 0x59, 0xed, 0xe5, 0xe0, 0xfc,
	0xf4, 0xb1, 0x53, 0x3b, 0xa3, 0x9a, 0x82, 0x9d, 0x68, 0x89, 0x55, 0xf8, 0x4f, 0xf9, 0xb0, 0xb1,
	0xb7, 0x0f, 0x6f, 0x78, 0x92, 0xee, 0xf5, 0xb2, 0x27, 0x79, 0xd7, 0x60, 0xad, 0x0b, 0x25, 0x2d,
	0xa8, 0x45, 0x37, 0x91, 0x63, 0x90, 0x27, 0x40, 0x22, 0xbd, 0x89, 0xdb, 0x24, 0x8c, 0xd5, 0x05,
	0xbf, 0x5d, 0x88, 0x7b, 0x1e, 0x38, 0x26, 0x39, 0x02, 0xa7, 0x98, 0x7f, 0xc9, 0xc4, 0x3d, 0x17,
	0x4e, 0x8d, 0x00, 0x34, 0xa3, 0x17, 0x42, 0x24, 0xc2, 0xa9, 0xf7, 0xbe, 0x5d, 0xbf, 0x4b, 0x95,
	0xad, 0x1a, 0xfb, 0x6d, 0xb5, 0x5a, 0xac, 0xb9, 0x61, 0xa0, 0xbd, 0xd7, 0x46, 0xe5, 0x4d, 0xf9,
	0x2b, 0x5f, 0xd8, 0x12, 0xd3, 0xfc, 0x13, 0x8f, 0x9a, 0xfe, 0x5d, 0xce, 0xc6, 0xf8, 0xf6, 0x74,
	0x68, 0x3e, 0xda, 0x12, 0x79, 0xa3, 0xee, 0xff, 0xd0, 0xd9, 0x4f, 0xa7, 0x50, 0xd7, 0x4e, 0x49,
	0xba, 0x60, 0x45, 0xab, 0x4b, 0xe3, 0x18, 0xa4, 0x03, 0xed, 0x28, 0xef, 0x4c, 0xc7, 0x24, 0x36,
	0xb4, 0xa2, 0xec, 0x98, 0x9c, 0x1a, 0x39, 0x04, 0x3b, 0x2a, 0x54, 0x75, 0xea, 0x48, 0xfd, 0x86,
	0x33, 0x75, 0xc1, 0x99, 0x72, 0x1a, 0x78, 0xe8, 0x1b, 0xe5, 0x3b, 0xcd, 0xd3, 0x63, 0x80, 0xc2,
	0x6c, 0x8b, 0xce, 0x29, 0x7a, 0xc1, 0xfc, 0x23, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x6d, 0xb1, 0x27,
	0x9e, 0x0c, 0x00, 0x00,
}
